apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-metrics-server-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-metrics-server-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "kube-metrics-server-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-metrics-server-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-metrics-server-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          {{- with $.Values.controller.extraArgs }}
          args: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.controller.env }}
          env:
          {{- range $key, $value := .Values.controller.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          {{- end }}
          {{- with $.Values.controller.ports }}
          ports: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.controller.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.controller.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.controller.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
