apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-metrics-server-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-metrics-server-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "kube-metrics-server-exporter.selectorLabels" . | nindent 4 }}
