apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-metrics-server-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-metrics-server-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceaccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
